name: Build and Deploy Azure Function App

on:
  push:
    branches:
      - main  # Change this to your branch name if it's not 'main'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Action
      uses: actions/checkout@v3

    - name: Setup .NET 8 Environment
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.0  # Use the latest version of .NET 8

    - name: Resolve Project Dependencies Using Dotnet
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Publish Project
      run: dotnet publish --configuration Release -o published

    - name: Deploy Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: testing001vk  # Replace with your Function App name
        package: published
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
