name: Build and Deploy Azure Function App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Install .NET SDK
      run: |
        curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 8.0
        echo "##[add-path]$HOME/.dotnet"
        export PATH="$HOME/.dotnet:$PATH"

    - name: Check Installed .NET Version
      run: dotnet --version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Publish Project
      run: dotnet publish --configuration Release -o published

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: testing001vk
        package: published
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
