name: Build and Deploy Azure Function App

on:
  push:
    branches:
      - main  # Adjust this if you're using a different branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup .NET 8 Isolated
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.0  # Use the latest .NET 8 version

    - name: Restore Dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Publish Project
      run: dotnet publish --configuration Release -o published

    - name: Deploy to Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: testing001vk  # Replace with your Function App name
        package: published
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
