name: Build and Deploy Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your Azure Function App project
  DOTNET_VERSION: '8.0.x' # Correct version format for .NET SDK

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK environment
      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} # Use the corrected version format
          include-prerelease: true # Enable preview versions if necessary

      # Step 3: Install dependencies and build
      - name: Build and Publish Project
        run: |
          dotnet restore ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
          dotnet build ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release
          dotnet publish ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }} --configuration Release --output ./output

      # Step 4: Deploy to Azure Function App
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'testing001vk' # Your Function App name
          package: './output' # Deployment package path
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
