name: Build and Deploy Azure Function App - testing001vk

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your Azure Function App project
  DOTNET_VERSION: '8.0.x' # Correct version format for .NET SDK

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Setup .NET SDK environment
      - name: Setup DotNet Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }} # Use .NET 8 SDK
          include-prerelease: true # Enable preview versions if needed

      # Step 3: Build the project
      - name: Build and Publish Project
        shell: bash
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./output
          popd

      # Step 4: Deploy to Azure Function App
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: 'testing001vk' # Your Function App name
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output' # Deployment package path
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }} # Publish profile secret
