name: Deploy Azure Function App

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
permissions:
  id-token: write # Required for federated credentials
  contents: read # Allows actions/checkout to work

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your Function App project
  DOTNET_VERSION: '8.0.x' # .NET version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up .NET environment
      - name: Setup .NET Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Step 3: Restore and build the project
      - name: Restore and Build .NET Project
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./output
          popd

      # Step 4: Azure login with Managed Identity
      - name: Azure Login with Federated Credential
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }} # Replace with Managed Identity Principal ID
          tenant-id: ${{ secrets.AZURE_TENANT_ID }} # Replace with your Azure Tenant ID
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }} # R
          enable-AZPSSession: true

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Azure PowerShell script
        uses: azure/powershell@v2
        with:
          azPSVersion: "latest"
          inlineScript: |
            Get-AzContext

      # Step 5: Deploy to Azure Function App
      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: testing001vk # Replace with your Function App name
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
