name: Build and Deploy Azure Function App - testing001vk

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.' # Path to your web app project
  DOTNET_VERSION: '8.0.x' # .NET version

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup .NET Environment
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
          include-prerelease: true

      - name: Restore and Build .NET Project
        run: |
          pushd './${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'
          dotnet restore
          dotnet build --configuration Release
          dotnet publish --configuration Release --output ./output
          popd

      - name: Azure Login with Federated Credential
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          auth-type: 'IDENTITY'

      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: testing001vk
          package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}/output'
